name: Godot Export

on: 
  push:
    branches:
      - master
  
env:
  GODOT_VERSION: 3.2.2
  EXPORT_NAME: dancefloor

jobs:
  export-windows-32-bits:
    name: Windows (32 bits) - Release
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:3.2.2
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: git
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Build
        run: |
          cd $GITHUB_WORKSPACE
          cd git
          mkdir -v -p build/windows/32
          cd $EXPORT_NAME
          godot -v --export "Windows Desktop (32 bits)" ../build/windows/32/$EXPORT_NAME.exe
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: windows-32bits
          path: build/windows/32